### ISSUE TITLE
Roadmap?

### ISSUE THREAD

**Issue by chip** [nelstrom/vimprint#3]
I would love to help, but not really sure where to start.  Is there some sort of roadmap for this project?

**Comment by nelstrom** [comment]
Thanks for your interest! I haven't written down a roadmap yet - it's all in my head - but I'll try and write it down soon. I'm looking for partners to [#pairwithme](http://www.pairprogramwith.me/), so give me a shout if you're into that idea.

**Comment by nelstrom** [comment]
More details to follow, but [this is a start](https://github.com/nelstrom/vimprint/blob/80173cf52eee11618164a478ba8767305f145e86/roadmap.md)
